import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";

test("uses the built-in Word format and exposes preview/export controls", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const exporter = await readFile(new URL("../lib/word-template.ts", import.meta.url), "utf8");
  const template = await stat(new URL("../public/templates/mountain-plan-template.docx", import.meta.url));

  assert.ok(template.size > 0);
  assert.match(page, /NAVITIMEで確認/);
  assert.match(page, /recalculate-budget/);
  assert.doesNotMatch(page, /Wordへ人が追記|標準書式.*準備済み/);
  assert.match(page, /Word出力プレビュー/);
  assert.doesNotMatch(page, /補足メモ|参照予定の情報|PLAN BUILD STATUS/);
  assert.doesNotMatch(page, /下書き保存|Markdown保存|templateFile|mountain-plan-draft/);
  assert.match(page, /fetch\("\/templates\/mountain-plan-template\.docx"/);
  assert.match(page, /fillWordTemplate\(await templateResponse\.arrayBuffer\(\), plan,/);
  assert.match(page, /renderAsync\(wordDocument, container\.current/);
  assert.match(page, /山行情報を<\/span><br \/>代わりに取得/);
  assert.match(page, /YAMARECO RESEARCH/);
  assert.match(page, /公開情報を取得/);
  assert.match(page, /USAGE_HISTORY_KEY/);
  assert.match(page, /usageHistory/);
  assert.match(page, /使った履歴/);
  assert.doesNotMatch(page, />URLを確認<\/button>/);
  assert.match(page, /yamareco-reference-pane/);
  assert.match(page, /yamareco-reference-frame/);
  assert.match(page, /yamarecoFrameSize/);
  assert.match(page, /YAMARECO_REFERENCE_WIDTH/);
  assert.match(page, /src=\{planUrl\}/);
  assert.match(page, /ヤマレコを閉じる/);
  assert.match(page, /ヤマレコを表示/);
  assert.match(page, /extraction-editor/);
  assert.match(page, /AI抽出結果の確認/);
  assert.match(page, /source-badge yamareco/);
  assert.match(page, /source-badge web/);
  assert.match(page, /source-badge manual/);
  assert.match(page, /editable-table/);
  assert.match(page, /rowSpan=\{itemSpan\}/);
  assert.doesNotMatch(page, /word-template-editor/);
  assert.doesNotMatch(page, /word-template-table/);
  assert.doesNotMatch(page, /rowSpan=\{7\}/);
  assert.match(page, /inline-citation-list/);
  assert.match(page, /buildTimetableCitations/);
  assert.match(page, /timetableCitationLinks/);
  assert.match(page, /yamarecoPlanUrl/);
  assert.match(page, /extractHttpsUrls/);
  assert.match(page, /generatedTimetableImages/);
  assert.match(page, /initialTimetableImages/);
  assert.match(page, /関係諸機関/);
  assert.match(page, /予算/);
  assert.match(styles, /extraction-editor/);
  assert.match(styles, /editor-section/);
  assert.match(styles, /schedule-field/);
  assert.match(styles, /history-toggle/);
  assert.doesNotMatch(exporter, /宿泊地URL/);
  assert.doesNotMatch(page, /function SourceLinks/);
  assert.doesNotMatch(page, /field-source-links/);
  assert.doesNotMatch(page, /source-preview/);
  assert.doesNotMatch(page, /source-chips/);
  assert.doesNotMatch(page, /sources-card/);
  assert.doesNotMatch(page, /宿泊施設の公式ページ/);
  assert.match(page, /collapseDuplicateAgencyLabels/);
  assert.match(page, /displayedOrganizations/);
  assert.match(exporter, /collapseDuplicateOrganizationLabels/);
  assert.match(exporter, /currentOrganizationItem/);
  assert.match(exporter, /setMergedCell/);
  assert.match(exporter, /vMerge/);
  assert.match(exporter, /setCellBorder/);
  assert.match(exporter, /hideBottom/);
  assert.match(exporter, /categoryMergeSpan/);
  assert.match(exporter, /yamarecoPlanUrl/);
  assert.match(exporter, /setCellTitleWithUrl/);
  assert.match(exporter, /appendLinksAfterBodyParagraph/);
  assert.match(exporter, /extractHttpsUrls/);
  const route = await readFile(new URL("../app/api/generate/route.ts", import.meta.url), "utf8");
  assert.match(route, /fetchTimetableImages/);
  assert.match(route, /extractHttpsUrls/);
  assert.match(route, /timetables: timetableImages\.map/);
  assert.match(exporter, /入山時刻：/);
  assert.match(exporter, /下山時刻：/);
  assert.match(exporter, /setScheduleColumns/);
  assert.match(exporter, /expandCellAcrossFollowingCells/);
  assert.match(exporter, /directRowCells/);
  assert.match(exporter, /gridCol/);
  assert.match(exporter, /insideV/);
  assert.match(exporter, /"pct"/);
  assert.match(exporter, /"5000"/);
  assert.match(exporter, /"2500"/);
  assert.match(exporter, /plan\.sunrise/);
  assert.match(exporter, /ensureTableRows/);
  assert.doesNotMatch(exporter, /時刻表：/);
  assert.doesNotMatch(exporter, /ヤマレコのルート地図を開く/);
  assert.doesNotMatch(exporter, /plan\.lodging && `宿泊：/);
  assert.doesNotMatch(exporter, /appendParagraph\(document, notesCell, "参照："/);
  assert.match(exporter, /appendImagesAfterBodyParagraph/);
  assert.match(exporter, /〈時刻表など〉/);
  assert.doesNotMatch(exporter, /fetch\(/);
});
